Numpy

In [9]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]

In [4]:
arr=np.array(my_list)

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

2 dimension

In [12]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
arr=np.array([my_list1,my_list2])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [15]:
arr.shape

(2, 5)

In [17]:
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [18]:
arr.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [ ]:
Retrieveing elments using index

In [22]:
my_array1=[1,2,3,4,5]
my_array2=[3,4,5,6,7]
my_array3=[7,8,9,3,4]

farr=np.array([my_array1,my_array2,my_array3])

In [23]:
farr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [7, 8, 9, 3, 4]])

In [24]:
farr[:,:] #retrieve all elements

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [7, 8, 9, 3, 4]])

In [25]:
farr[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [26]:
farr[1:,1:4]

array([[4, 5, 6],
       [8, 9, 3]])

In [29]:
arr=np.arange(0,10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr=np.arange(0,10,2)

In [33]:
arr

array([0, 2, 4, 6, 8])

In [34]:
arr=np.linspace(0,12,50)

In [35]:
arr

array([ 0.        ,  0.24489796,  0.48979592,  0.73469388,  0.97959184,
        1.2244898 ,  1.46938776,  1.71428571,  1.95918367,  2.20408163,
        2.44897959,  2.69387755,  2.93877551,  3.18367347,  3.42857143,
        3.67346939,  3.91836735,  4.16326531,  4.40816327,  4.65306122,
        4.89795918,  5.14285714,  5.3877551 ,  5.63265306,  5.87755102,
        6.12244898,  6.36734694,  6.6122449 ,  6.85714286,  7.10204082,
        7.34693878,  7.59183673,  7.83673469,  8.08163265,  8.32653061,
        8.57142857,  8.81632653,  9.06122449,  9.30612245,  9.55102041,
        9.79591837, 10.04081633, 10.28571429, 10.53061224, 10.7755102 ,
       11.02040816, 11.26530612, 11.51020408, 11.75510204, 12.        ])

copy and markdown

In [36]:
list=[1,2,3,4,5,6]
arr1=np.array(list)

In [37]:
arr1

array([1, 2, 3, 4, 5, 6])

In [38]:
arr1[2:]=500

In [39]:
arr1

array([  1,   2, 500, 500, 500, 500])

In [40]:
arr2=arr1

In [41]:
arr2[2:]=1000

In [42]:
arr2

array([   1,    2, 1000, 1000, 1000, 1000])

In [43]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000])

In [47]:
arr2=arr1.copy()

In [49]:
arr2[:2]=99
arr2

array([  99,   99, 1000, 1000, 1000, 1000])

In [50]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000])

In [51]:
arr1<2

array([ True, False, False, False, False, False])

In [53]:
arr1*2

array([   2,    4, 2000, 2000, 2000, 2000])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
np.random.randn(3,3)

array([[ 1.96399368, -1.62525971, -0.00344095],
       [-0.14120355, -0.44727192,  0.26309115],
       [ 0.71578671,  0.83084089, -0.88848908]])

In [57]:
np.random.rand(3,3)

array([[0.28291814, 0.72243852, 0.47006291],
       [0.25139743, 0.84720058, 0.04952989],
       [0.17377529, 0.61696512, 0.66103198]])

In [59]:
np.random.randint(0,100,8)

array([24, 99, 99, 54, 95, 57,  2, 40])

Pandas

In [8]:
import pandas as pd

In [10]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['column1','column2','column3','column4'])

In [11]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [12]:
df.loc['Row1']

column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int32

In [13]:
type(df.loc['Row1'])

pandas.core.series.Series

In [14]:
df.iloc[:,:].values.shape

(5, 4)

In [15]:
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [16]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [17]:
df['column3'].unique()

array([ 2,  6, 10, 14, 18])

In [18]:
df['column3'].value_counts()

column3
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [19]:
df['column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int32

In [20]:
df[['column1','column2']]

column1  column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [21]:
df=pd.read_csv('train.csv')

In [22]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [24]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [25]:
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [26]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [27]:
from io import StringIO,BytesIO

In [36]:
data=('co1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [37]:
type(data)

str

In [38]:
pd.read_csv(StringIO(data))

co1 col2  col3
0   x    y     1
1   a    b     2
2   c    d     3

In [40]:
df=pd.read_csv(StringIO(data),usecols=['co1','col2'],dtype=object)

In [41]:
df

co1 col2
0   x    y
1   a    b
2   c    d

In [44]:
df['co1'][1]

'a'

In [63]:
value=('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '4,6,2,7')

In [64]:
df=pd.read_csv(StringIO(value),dtype={'b':int,'c':float,'d':'Int64'})

In [65]:
df

a  b    c  d
0  1  2  3.0  4
1  5  6  7.0  8
2  4  6  2.0  7

In [67]:
type(df['d'][2])

numpy.int64

In [68]:
df.dtypes

a      int64
b      int32
c    float64
d      Int64
dtype: object

In [72]:
df

a  b  c
0  1  2  3
1  4  5  6

In [83]:
mel=('a,b,c\n'
     '2,orange,banana,\n'
     '4,chikku,apple')

In [86]:
df=pd.read_csv(StringIO(mel),index_col=False)

In [87]:
df

a       b       c
0  2  orange  banana
1  4  chikku   apple

In [88]:
data='a,b\n"Hello, \\"Bob\\",nice",5'

In [90]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  Hello, "Bob",nice  5

JSON

In [104]:
data='{"name":"james", "email":"melanie@gmail.com", "job":[{"title":"team"}]}'


In [106]:
df=pd.read_json(StringIO(data))

In [107]:
df

name              email                job
0  james  melanie@gmail.com  {'title': 'team'}

In [108]:
df.to_json()

'{"name":{"0":"james"},"email":{"0":"melanie@gmail.com"},"job":{"0":{"title":"team"}}}'

In [110]:
df.to_json(orient="records")

'[{"name":"james","email":"melanie@gmail.com","job":{"title":"team"}}]'

HTML

In [113]:
url='https://en.wikipedia.org/wiki/Mobile_country_code'

In [116]:
dfs=pd.read_html(url,match='country',header=0)

In [118]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]